services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
      args:
        USERNAME: CAPITAL
        USERID: 197609
    container_name: eic_m_s
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - .:/home/user/workspace
    ports:
      - "8080:8000"
    environment:
      PS1: "[ $$(whoami) | \\w ] "
